name: Delete Files

on:
  workflow_dispatch:

jobs:
  delete-files:
    runs-on: ubuntu-latest
    env:
      FILES: ${{ env.TO_DELETED }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Display directory names
        id: display-directories
        run: |
          set -x
          for file in $FILES; do
            find . -type f -name "target_$file.yaml" -exec dirname {} \; | sort -u
          done

      - name: Find and delete files
        id: find-delete-files
        run: |
          set -x
          for file in $(echo ${{ env.FILES }} | tr "," "\n"); do
            find . -type f -name "target_${file}.yaml" -delete
          done


